version: '3'
services:
  app:
    container_name: signinwithjwt
    build: .
    ports: 
      - 8080:8080 
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - postgres
    networks:
      - signinjwt


  postgres:
    image: postgres:latest
    container_name: postgresdb
    environment:
      - POSTGRES_USER=postgres  
      - POSTGRES_PASSWORD=Anirudh@123
      - POSTGRES_DB=Densityasmt
    ports:
      - '5435:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - signinjwt
    
#  pgadmin:
#    image: dpage/pgadmin4
#    container_name: pgadmin_container
#    environment:
#      PGADMIN_DEFAULT_EMAIL: codewithanirudhagni@gmail.com
#      PGADMIN_DEFAULT_PASSWORD: Anirudh@123
#    depends_on:
#      - postgres
#    ports:
#      - "5050:80"
#    networks:
#      - signinjwt
#    restart: unless-stopped

volumes:
  api:
  database_postgres:                  

# Networks to be created to facilitate communication between containers
networks:
  signinjwt:
    driver: bridge

    